In [137]:
import pandas as pd

In [138]:
df = pd.read_csv("../../raw/djt_posts_dec2025.csv")
df.head(10)

,id,date,platform,handle,text,favorite_count,repost_count,quote_flag,repost_flag,deleted_flag,word_count,hashtags,urls,user_mentions,media_count,media_urls,post_url,in_reply_to
0,115816402893182666,2025-12-31 21:54:21+00:00,Truth Social,realDonaldTrump,"Good News! George and Amal Clooney, two of the...",52,16,False,False,False,144,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
1,115816171466225987,2025-12-31 20:55:30+00:00,Truth Social,realDonaldTrump,We are removing the National Guard from Chicag...,44,16,False,False,False,107,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
2,115816098525451632,2025-12-31 20:36:57+00:00,Truth Social,realDonaldTrump,The Democrats are a bunch of cheaters and thie...,461,179,False,False,False,50,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
3,115816063544553030,2025-12-31 20:28:03+00:00,Truth Social,realDonaldTrump,Republicans: No more money to Fat Cat Insuranc...,309,97,False,False,False,24,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
4,115815971019162695,2025-12-31 20:04:31+00:00,Truth Social,realDonaldTrump,The United States has set a World Record on in...,36,11,False,False,False,76,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
5,115815655902009476,2025-12-31 18:44:23+00:00,Truth Social,realDonaldTrump,A total FRAUD! \nMinnesota Somali-run day care...,165,69,False,False,False,24,NaN,https://nypost.com/2025/12/31/us-news/minnesot...,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
6,115815651158028007,2025-12-31 18:43:11+00:00,Truth Social,realDonaldTrump,Minnesota day care scandal sparks concern over...,193,69,False,False,False,23,NaN,https://nypost.com/2025/12/31/us-news/minnesot...,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
7,115815648382815071,2025-12-31 18:42:28+00:00,Truth Social,realDonaldTrump,Putin ‘attack’ bluster shows Russia is the one...,56,20,False,False,False,17,NaN,https://nypost.com/2025/12/30/opinion/putin-at...,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
8,115815610061050583,2025-12-31 18:32:44+00:00,Truth Social,realDonaldTrump,Douglas Murray: Trump cleaned up crime in DC –...,11,2,False,False,False,20,NaN,https://nypost.com/2025/12/18/opinion/douglas-...,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN
9,115815355325954705,2025-12-31 17:27:57+00:00,Truth Social,realDonaldTrump,"God Bless Tina Peters, who is now, for two yea...",189,82,False,False,False,115,NaN,NaN,NaN,0,NaN,https://truthsocial.com/@realDonaldTrump/posts...,NaN

### we don't need the truthsocial posts anymore, we will delete them to only keep X tweets

In [139]:
df['platform'].unique()

<ArrowStringArray>
['Truth Social', 'Twitter']
Length: 2, dtype: str

In [140]:
df = df[df['platform'] == 'Twitter']

In [141]:
df.head(10)

,id,date,platform,handle,text,favorite_count,repost_count,quote_flag,repost_flag,deleted_flag,word_count,hashtags,urls,user_mentions,media_count,media_urls,post_url,in_reply_to
199,2004012442427277591,2025-12-25 02:12:53+00:00,Twitter,realDonaldTrump,"Merry Christmas to all, including the Radical ...",20404,0,False,False,False,47,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/200401244...,NaN
214,2003565251816554746,2025-12-23 20:35:55+00:00,Twitter,realDonaldTrump,THE TRUMP KENNEDY CENTER HONORS will be broadc...,4996,0,False,False,False,51,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/200356525...,NaN
447,1995898845134303294,2025-12-02 16:52:21+00:00,Twitter,realDonaldTrump,I am asking all America First Patriots in Tenn...,2151,0,False,False,False,48,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199589884...,NaN
614,1995676855651664182,2025-12-02 02:10:14+00:00,Twitter,realDonaldTrump,I am asking all America First Patriots in Tenn...,6497,0,False,False,False,47,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199567685...,NaN
649,1994760100376891748,2025-11-29 13:27:23+00:00,Twitter,realDonaldTrump,"To all Airlines, Pilots, Drug Dealers, and Hum...",17535,0,False,False,False,35,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199476010...,NaN
661,1994438728237064270,2025-11-28 16:10:22+00:00,Twitter,realDonaldTrump,The United States did not attend the G20 in So...,6068,0,False,False,False,45,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199443872...,NaN
662,1994438342403141889,2025-11-28 16:08:50+00:00,Twitter,realDonaldTrump,Democracy is on trial in the coming Elections ...,5653,0,False,False,False,45,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199443834...,NaN
665,1994272683387687053,2025-11-28 05:10:34+00:00,Twitter,realDonaldTrump,A very Happy Thanksgiving salutation to all of...,4160,0,False,False,False,44,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199427268...,NaN
673,1993801758326616561,2025-11-26 21:59:16+00:00,Twitter,realDonaldTrump,https://t.co/oQK0HLgf88,1095,0,False,False,False,1,NaN,NaN,NaN,1,https://pbs.twimg.com/media/G6toIexXAAAuXuy.jpg,https://x.com/realdonaldtrump/status/199380175...,NaN
699,1993469230528790869,2025-11-25 23:57:56+00:00,Twitter,realDonaldTrump,I am asking all America First Patriots in Tenn...,4377,0,False,False,False,49,NaN,NaN,NaN,0,NaN,https://x.com/realdonaldtrump/status/199346923...,NaN

#### We're gonna only look at data up unitl 2022-02-14
&rarr; this is becausse trump posts on truthsocial foro this date

In [142]:
print(df['date'].min())
print(df['date'].max())

2009-05-04 18:54:25+00:00
2025-12-25 02:12:53+00:00

In [143]:
df = df[df['date'] < '2022-02-14']

In [144]:
print(df['date'].min())
print(df['date'].max())

2009-05-04 18:54:25+00:00
2021-01-08 15:44:28+00:00

In [145]:
print(f"total tweets of twitter: {len(df)}")

total tweets of twitter: 58248

## Filtering data

#### we gaan data eruit halen waarbij de text empty is 
#### we houden ook enkel de date, text, username en url

In [146]:
df = df[['date', 'handle','text', 'post_url']].dropna(subset=['text'])

In [147]:
print(f"total tweets after filtering of twitter: {len(df)}")

total tweets after filtering of twitter: 58248

##### all text columns has a value

In [148]:
print(len(df[df['text'] == '']))

0

we also want to delete all the tweets that only have a link as the text

In [149]:
df.head()

,date,handle,text,post_url
32095,2021-01-08 15:44:28+00:00,realDonaldTrump,"To all of those who have asked, I will not be ...",https://x.com/realdonaldtrump/status/134756987...
32096,2021-01-08 14:46:38+00:00,realDonaldTrump,"The 75,000,000 great American Patriots who vot...",https://x.com/realdonaldtrump/status/134755531...
32097,2021-01-08 00:10:24+00:00,realDonaldTrump,https://t.co/csX07ZVWGe,https://x.com/realdonaldtrump/status/134733480...
32098,2021-01-06 23:01:04+00:00,realDonaldTrump,These are the things and events that happen wh...,https://x.com/realdonaldtrump/status/134695497...
32099,2021-01-06 21:17:24+00:00,realDonaldTrump,https://t.co/Pm2PKV0Fp3,https://x.com/realdonaldtrump/status/134692888...

In [150]:
import re

df = df[
    ~df['text'].str.fullmatch(r'https?://\S+', na=False)
]

In [151]:
print(f"total tweets after filtering of twitter: {len(df)}")

total tweets after filtering of twitter: 57606

In [152]:
df.head()

,date,handle,text,post_url
32095,2021-01-08 15:44:28+00:00,realDonaldTrump,"To all of those who have asked, I will not be ...",https://x.com/realdonaldtrump/status/134756987...
32096,2021-01-08 14:46:38+00:00,realDonaldTrump,"The 75,000,000 great American Patriots who vot...",https://x.com/realdonaldtrump/status/134755531...
32098,2021-01-06 23:01:04+00:00,realDonaldTrump,These are the things and events that happen wh...,https://x.com/realdonaldtrump/status/134695497...
32100,2021-01-06 20:13:26+00:00,realDonaldTrump,I am asking for everyone at the U.S. Capitol t...,https://x.com/realdonaldtrump/status/134691278...
32101,2021-01-06 19:38:58+00:00,realDonaldTrump,Please support our Capitol Police and Law Enfo...,https://x.com/realdonaldtrump/status/134690411...

In [153]:
df.columns = [col.capitalize() for col in df.columns]

### make datekey,TimeKey and renaming columns to match database

In [154]:
df['Date'] = pd.to_datetime(df['Date'])


df['DateKey'] = df['Date'].dt.strftime('%Y%m%d')
df['TimeKey'] = df['Date'].dt.strftime('%H%M%S')

In [155]:
df.drop(columns=['Date'],inplace=True)

In [156]:
df.rename(columns={
    'Post_url' : 'url',
    'Handle' : "UserName"
},inplace=True)

In [157]:
df.head()

,UserName,Text,url,DateKey,TimeKey
32095,realDonaldTrump,"To all of those who have asked, I will not be ...",https://x.com/realdonaldtrump/status/134756987...,20210108,154428
32096,realDonaldTrump,"The 75,000,000 great American Patriots who vot...",https://x.com/realdonaldtrump/status/134755531...,20210108,144638
32098,realDonaldTrump,These are the things and events that happen wh...,https://x.com/realdonaldtrump/status/134695497...,20210106,230104
32100,realDonaldTrump,I am asking for everyone at the U.S. Capitol t...,https://x.com/realdonaldtrump/status/134691278...,20210106,201326
32101,realDonaldTrump,Please support our Capitol Police and Law Enfo...,https://x.com/realdonaldtrump/status/134690411...,20210106,193858

In [158]:
df['DateKey'] = df['DateKey'].astype(int)
df['TimeKey'] = df['TimeKey'].astype(int)

In [159]:
df.info()

<class 'pandas.DataFrame'>
Index: 57606 entries, 32095 to 90342
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   UserName  57606 non-null  str
 1   Text      57606 non-null  str
 2   url       57606 non-null  str
 3   DateKey   57606 non-null  int64
 4   TimeKey   57606 non-null  int64
dtypes: int64(2), str(3)
memory usage: 13.8 MB

### save

In [161]:
df.to_csv("../../processed/trump_twitter.csv", index=False)

In [ ]:
df['DateKey'].min()

np.int64(20090504)

: