In [2]:
import pandas as pd
import sys
from pathlib import Path

In [3]:
ROOT = Path().resolve().parents[3]
sys.path.append(str(ROOT))

print(ROOT)

C:\Users\Luizv\Documents\HoGent\jaar3\BachelorProef\BachelorProef2026

In [4]:
DATASET = ROOT / 'data' / 'raw' / 'tweets' / 'elonmusk' / 'all_musk_posts2010-2025.csv'

In [5]:
df = pd.read_csv(DATASET)
df.head(10)

C:\Users\Luizv\AppData\Local\Temp\ipykernel_10676\1387692871.py:1: DtypeWarning: Columns (0: isReply, 1: isPinned, 2: isRetweet, 3: isQuote, 4: isConversationControlled) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATASET)

,id,url,twitterUrl,fullText,retweetCount,replyCount,likeCount,quoteCount,viewCount,createdAt,...,inReplyToUserId,inReplyToUsername,isPinned,isRetweet,isQuote,isConversationControlled,possiblySensitive,quoteId,quote,retweet
0,1655159652990976000,https://x.com/elonmusk/status/1655159652990976000,https://twitter.com/elonmusk/status/1655159652...,RT @einarvollset: I read @paulg’s “How to Mak...,NaN,NaN,NaN,NaN,NaN,2023-05-07 10:36:27+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1657261624867299339,https://x.com/elonmusk/status/1657261624867299339,https://twitter.com/elonmusk/status/1657261624...,https://t.co/Zjn6r15lrR,NaN,NaN,NaN,NaN,NaN,2023-05-13 05:48:56+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1623774484795920384,https://x.com/elonmusk/status/1623774484795920384,https://twitter.com/elonmusk/status/1623774484...,RT @BillyM2k: dude bookmarks are an awesome tw...,NaN,NaN,NaN,NaN,NaN,2023-02-09 20:03:00+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1656900119202254854,https://x.com/elonmusk/status/1656900119202254854,https://twitter.com/elonmusk/status/1656900119...,Event Horizon Balance Beam,NaN,NaN,NaN,NaN,NaN,2023-05-12 05:52:26+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1616531874763116544,https://x.com/elonmusk/status/1616531874763116544,https://twitter.com/elonmusk/status/1616531874...,RT @BillyM2k: @elonmusk oh that’s actually pre...,NaN,NaN,NaN,NaN,NaN,2023-01-20 20:23:27+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1608035930983604230,https://x.com/elonmusk/status/1608035930983604230,https://twitter.com/elonmusk/status/1608035930...,RT @SpaceX: Watch Falcon 9 launch 54 Starlink ...,NaN,NaN,NaN,NaN,NaN,2022-12-28 09:43:36+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1602885009647366144,https://x.com/elonmusk/status/1602885009647366144,https://twitter.com/elonmusk/status/1602885009...,RT @Tesla: Holiday Update rolling out now 🎅,NaN,NaN,NaN,NaN,NaN,2022-12-14 04:35:41+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1643021267157803008,https://x.com/elonmusk/status/1643021267157803008,https://twitter.com/elonmusk/status/1643021267...,@davidmweissman The Internetz,NaN,NaN,NaN,NaN,NaN,2023-04-03 22:42:50+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1643002171942916096,https://x.com/elonmusk/status/1643002171942916096,https://twitter.com/elonmusk/status/1643002171...,https://t.co/Of6pyGjmHp,NaN,NaN,NaN,NaN,NaN,2023-04-03 21:26:57+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1642996528381042688,https://x.com/elonmusk/status/1642996528381042688,https://twitter.com/elonmusk/status/1642996528...,@BillyM2k What a tool,NaN,NaN,NaN,NaN,NaN,2023-04-03 21:04:32+00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55099 entries, 0 to 55098
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        55099 non-null  int64
 1   url                       55099 non-null  str
 2   twitterUrl                55099 non-null  str
 3   fullText                  55099 non-null  str
 4   retweetCount              55009 non-null  float64
 5   replyCount                54297 non-null  float64
 6   likeCount                 55009 non-null  float64
 7   quoteCount                54271 non-null  float64
 8   viewCount                 34455 non-null  float64
 9   createdAt                 55099 non-null  str
 10  bookmarkCount             54271 non-null  float64
 11  isReply                   54271 non-null  object
 12  inReplyToId               39497 non-null  float64
 13  conversationId            54297 non-null  float64
 14  inReplyToUserId           39521 non-null  float64
 15  inReplyToUsername         39521 non-null  str
 16  isPinned                  54271 non-null  object
 17  isRetweet                 55009 non-null  object
 18  isQuote                   54983 non-null  object
 19  isConversationControlled  54271 non-null  object
 20  possiblySensitive         4921 non-null   object
 21  quoteId                   7541 non-null   float64
 22  quote                     7273 non-null   str
 23  retweet                   1092 non-null   str
dtypes: float64(10), int64(1), object(6), str(7)
memory usage: 10.1+ MB

In [7]:
df.describe()

,id,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,inReplyToId,conversationId,inReplyToUserId,quoteId
count,5.509900e+04,55009.000000,54297.000000,5.500900e+04,54271.000000,3.445500e+04,54271.000000,3.949700e+04,5.429700e+04,3.952100e+04,7.541000e+03
mean,1.565238e+18,5152.859841,2375.592685,4.154156e+04,485.358442,8.839065e+06,810.181478,1.572386e+18,1.574776e+18,4.650182e+17,1.790196e+18
std,3.538849e+17,14041.809886,6747.502876,1.064703e+05,3075.282293,1.879434e+07,3479.675005,3.104468e+17,3.446097e+17,6.253846e+17,2.077654e+17
min,1.543473e+10,0.000000,0.000000,0.000000e+00,0.000000,1.000000e+00,0.000000,1.659576e+09,1.659576e+09,1.200000e+01,1.659601e+09
25%,1.402685e+18,80.000000,102.000000,1.351000e+03,8.000000,6.829150e+04,12.000000,1.419324e+18,1.419782e+18,4.419640e+07,1.806650e+18
50%,1.687677e+18,276.000000,271.000000,4.198000e+03,29.000000,2.489050e+05,32.000000,1.672634e+18,1.691963e+18,9.401079e+08,1.855711e+18
75%,1.832968e+18,2608.000000,1478.000000,2.858800e+04,205.000000,8.024403e+06,180.500000,1.805232e+18,1.834187e+18,1.106321e+18,1.886091e+18
max,1.911532e+18,610842.000000,357538.000000,4.372808e+06,439431.000000,6.071525e+08,161373.000000,1.906943e+18,1.911532e+18,1.901635e+18,1.911425e+18

In [8]:
for col in df.columns:
    missing_pct = df[col].isna().mean() * 100
    print(f"{col}: {missing_pct:.2f}% missing")

id: 0.00% missing
url: 0.00% missing
twitterUrl: 0.00% missing
fullText: 0.00% missing
retweetCount: 0.16% missing
replyCount: 1.46% missing
likeCount: 0.16% missing
quoteCount: 1.50% missing
viewCount: 37.47% missing
createdAt: 0.00% missing
bookmarkCount: 1.50% missing
isReply: 1.50% missing
inReplyToId: 28.32% missing
conversationId: 1.46% missing
inReplyToUserId: 28.27% missing
inReplyToUsername: 28.27% missing
isPinned: 1.50% missing
isRetweet: 0.16% missing
isQuote: 0.21% missing
isConversationControlled: 1.50% missing
possiblySensitive: 91.07% missing
quoteId: 86.31% missing
quote: 86.80% missing
retweet: 98.02% missing

In [9]:
df = df[['createdAt','url','fullText','retweetCount','replyCount','likeCount']]

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55099 entries, 0 to 55098
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   createdAt     55099 non-null  str
 1   url           55099 non-null  str
 2   fullText      55099 non-null  str
 3   retweetCount  55009 non-null  float64
 4   replyCount    54297 non-null  float64
 5   likeCount     55009 non-null  float64
dtypes: float64(3), str(3)
memory usage: 2.5 MB

In [11]:
df.rename(columns={
    'retweetCount' : "Reposts",
    'replyCount' : 'Comments',
    'likeCount' : 'Likes'
},inplace=True)

In [12]:
df = df[~df['fullText'].str.startswith("RT", na=False)]

In [13]:
for i in df['url']:
    print(i)

https://x.com/elonmusk/status/1657261624867299339
https://x.com/elonmusk/status/1656900119202254854
https://x.com/elonmusk/status/1643021267157803008
https://x.com/elonmusk/status/1643002171942916096
https://x.com/elonmusk/status/1642996528381042688
https://x.com/elonmusk/status/1639022301973970944
https://x.com/elonmusk/status/1633159188787658757
https://x.com/elonmusk/status/1633155636996485120
https://x.com/elonmusk/status/1632578926936571904
https://x.com/elonmusk/status/1624920846166007808
https://x.com/elonmusk/status/1621988107603116033
https://x.com/elonmusk/status/1552106724366090246
https://x.com/elonmusk/status/1552101512544919553
https://x.com/elonmusk/status/1551955376295256064
https://x.com/elonmusk/status/1551629246661120000
https://x.com/elonmusk/status/1605352537233694721
https://x.com/elonmusk/status/1604345722001817600
https://x.com/elonmusk/status/1602948868248936448
https://x.com/elonmusk/status/1527793145097900036
https://x.com/elonmusk/status/1596076414138306560
https://x.com/elonmusk/status/1591585984747286528
https://x.com/elonmusk/status/1585289655431229440
https://x.com/elonmusk/status/1576976609348681738
https://x.com/elonmusk/status/1567726195671797766
https://x.com/elonmusk/status/1567723610197852160
https://x.com/elonmusk/status/1567722560443355141
https://x.com/elonmusk/status/1563340246682849281
https://x.com/elonmusk/status/1563337811578978305
https://x.com/elonmusk/status/1671704599219130369
https://x.com/elonmusk/status/1669162882859433984
https://x.com/elonmusk/status/1668703764897775616
https://x.com/elonmusk/status/1668087309030379522
https://x.com/elonmusk/status/1667601876135686147
https://x.com/elonmusk/status/1666484466506760193
https://x.com/elonmusk/status/1665352062735900672
https://x.com/elonmusk/status/1664742794135470083
https://x.com/elonmusk/status/1664624015602769920
https://x.com/elonmusk/status/1661216481206763520
https://x.com/elonmusk/status/1659437169168076800
https://x.com/elonmusk/status/1659417257699688448
https://x.com/elonmusk/status/1654692917410185218
https://x.com/elonmusk/status/1651096664034144256
https://x.com/elonmusk/status/1648787284429352964
https://x.com/elonmusk/status/1648456965922902019
https://x.com/elonmusk/status/1644963396301848576
https://x.com/elonmusk/status/1640415140410474500
https://x.com/elonmusk/status/1636919544483655680
https://x.com/elonmusk/status/1636650611457261570
https://x.com/elonmusk/status/1628994840665923584
https://x.com/elonmusk/status/1627247215059124228
https://x.com/elonmusk/status/1622627861013180417
https://x.com/elonmusk/status/1621397472756256770
https://x.com/elonmusk/status/1618404184856080384
https://x.com/elonmusk/status/1616592077831426048
https://x.com/elonmusk/status/1613546654107598849
https://x.com/elonmusk/status/1609641851837108224
https://x.com/elonmusk/status/1605275881181794311
https://x.com/elonmusk/status/1599669828478185472
https://x.com/elonmusk/status/1597275311577890816
https://x.com/elonmusk/status/1595294061694373889
https://x.com/elonmusk/status/1588989650353680385
https://x.com/elonmusk/status/1572396931866918914
https://x.com/elonmusk/status/1564995664408219648
https://x.com/elonmusk/status/1551013753700753409
https://x.com/elonmusk/status/1526813672382861313
https://x.com/elonmusk/status/1518218293680783360
https://x.com/elonmusk/status/1516168605934698498
https://x.com/elonmusk/status/1503693669823614983
https://x.com/elonmusk/status/1500316700922757123
https://x.com/elonmusk/status/1475076745627938821
https://x.com/elonmusk/status/1472123381889835009
https://x.com/elonmusk/status/1468633486097539078
https://x.com/elonmusk/status/1455327010302087173
https://x.com/elonmusk/status/1444361244996259843
https://x.com/elonmusk/status/1409152382345244684
https://x.com/elonmusk/status/1400654905149476865
https://x.com/elonmusk/status/928675794372608000
https://x.com/elonmusk/status/928335114353831936
https://x.com/elonmusk/status/924389383792312448
https://x.com/elonmusk/status/924387972161552512
https://x.com/elonmusk/status/923576364652953600
https://x.com/elonmusk/status/923469108917756032
https://x.com/elonmusk/status/923339941957976064
https://x.com/elonmusk/status/922828793152229248
https://x.com/elonmusk/status/921575999384326144
https://x.com/elonmusk/status/921419557918597248
https://x.com/elonmusk/status/921183170757738496
https://x.com/elonmusk/status/921050992707190912
https://x.com/elonmusk/status/920864873940107264
https://x.com/elonmusk/status/920845980467163136
https://x.com/elonmusk/status/920844783542853632
https://x.com/elonmusk/status/920834201535914112
https://x.com/elonmusk/status/920482298327216000
https://x.com/elonmusk/status/919999012899454848
https://x.com/elonmusk/status/919980024366632832
https://x.com/elonmusk/status/919675564423708672
https://x.com/elonmusk/status/918518924475379712
https://x.com/elonmusk/status/918517097839202432
https://x.com/elonmusk/status/918516707735437312
https://x.com/elonmusk/status/918314470048382848
https://x.com/elonmusk/status/918313446550265856
https://x.com/elonmusk/status/918003287600668672
https://x.com/elonmusk/status/917154829008605312
https://x.com/elonmusk/status/916406412112039936
https://x.com/elonmusk/status/916402688127930368
https://x.com/elonmusk/status/916401512661663744
https://x.com/elonmusk/status/916399837129564032
https://x.com/elonmusk/status/916397212891877248
https://x.com/elonmusk/status/916396499310751744
https://x.com/elonmusk/status/916395155120205824
https://x.com/elonmusk/status/916376799466024832
https://x.com/elonmusk/status/916336207935635456
https://x.com/elonmusk/status/916030871232176000
https://x.com/elonmusk/status/915990261938786432
https://x.com/elonmusk/status/915831795446190080
https://x.com/elonmusk/status/915453138051768448
https://x.com/elonmusk/status/914734726493102080
https://x.com/elonmusk/status/913669661505544192
https://x.com/elonmusk/status/913649379281534848
https://x.com/elonmusk/status/913642747197743232
https://x.com/elonmusk/status/913600101460955136
https://x.com/elonmusk/status/913595413546008448
https://x.com/elonmusk/status/913547943646580736
https://x.com/elonmusk/status/913489555663269888
https://x.com/elonmusk/status/912506866919288832
https://x.com/elonmusk/status/912259150175813632
https://x.com/elonmusk/status/912258562293825536
https://x.com/elonmusk/status/908715328112271232
https://x.com/elonmusk/status/908108029777686400
https://x.com/elonmusk/status/907483778603294848
https://x.com/elonmusk/status/907407613930827648
https://x.com/elonmusk/status/906274454946402432
https://x.com/elonmusk/status/904764676118012032
https://x.com/elonmusk/status/904764437281685632
https://x.com/elonmusk/status/904656511334354944
https://x.com/elonmusk/status/904641970349285248
https://x.com/elonmusk/status/904639405440323712
https://x.com/elonmusk/status/904633522161278848
https://x.com/elonmusk/status/903332343108092032
https://x.com/elonmusk/status/903132822700867712
https://x.com/elonmusk/status/903120412007047168
https://x.com/elonmusk/status/902913054723022848
https://x.com/elonmusk/status/902912866335956992
https://x.com/elonmusk/status/902810547384496000
https://x.com/elonmusk/status/902452162625544192
https://x.com/elonmusk/status/902088347840950272
https://x.com/elonmusk/status/902078189891026944
https://x.com/elonmusk/status/902077101334904832
https://x.com/elonmusk/status/902036110129250432
https://x.com/elonmusk/status/901975117797851136
https://x.com/elonmusk/status/901965739745148800
https://x.com/elonmusk/status/901930363118747648
https://x.com/elonmusk/status/901929826918981632
https://x.com/elonmusk/status/901904354126520448
https://x.com/elonmusk/status/901903526061907968
https://x.com/elonmusk/status/901902674853068800
https://x.com/elonmusk/status/901887665662025600
https://x.com/elonmusk/status/901875780556226432
https://x.com/elonmusk/status/901238166237069312
https://x.com/elonmusk/status/901236337281454080
https://x.com/elonmusk/status/901162747865333632
https://x.com/elonmusk/status/900958153533042688
https://x.com/elonmusk/status/900954066292924416
https://x.com/elonmusk/status/900953175594639232
https://x.com/elonmusk/status/900952880118603648
https://x.com/elonmusk/status/900952521560121344
https://x.com/elonmusk/status/900376843210981376
https://x.com/elonmusk/status/899701180674187264
https://x.com/elonmusk/status/899075756508065792
https://x.com/elonmusk/status/899017770787979264
https://x.com/elonmusk/status/898523896952922112
https://x.com/elonmusk/status/898522857847652352
https://x.com/elonmusk/status/897234747025313792
https://x.com/elonmusk/status/896762461574938624
https://x.com/elonmusk/status/896166762361704448
https://x.com/elonmusk/status/896163163581825024
https://x.com/elonmusk/status/895878249389072384
https://x.com/elonmusk/status/895872939286872064
https://x.com/elonmusk/status/895866249669820416
https://x.com/elonmusk/status/895865506602692608
https://x.com/elonmusk/status/895864765980958720
https://x.com/elonmusk/status/893982228857761792
https://x.com/elonmusk/status/893981677437018112
https://x.com/elonmusk/status/893176500005908480
https://x.com/elonmusk/status/892083176897626112
https://x.com/elonmusk/status/891719659514245120
https://x.com/elonmusk/status/891714878494261248
https://x.com/elonmusk/status/891546920232943616
https://x.com/elonmusk/status/891543170160353280
https://x.com/elonmusk/status/891108035665338368
https://x.com/elonmusk/status/890830152124563456
https://x.com/elonmusk/status/890765027032039424
https://x.com/elonmusk/status/890676198874824704
https://x.com/elonmusk/status/890096103135358976
https://x.com/elonmusk/status/889751762944512000
https://x.com/elonmusk/status/889736220116254720
https://x.com/elonmusk/status/888813713800785920
https://x.com/elonmusk/status/888137602108448768
https://x.com/elonmusk/status/888059982586839040
https://x.com/elonmusk/status/888058745153912832
https://x.com/elonmusk/status/888053175155949568
https://x.com/elonmusk/status/887035171542753280
https://x.com/elonmusk/status/887012021232820224
https://x.com/elonmusk/status/886011377357160448
https://x.com/elonmusk/status/885921115435974656
https://x.com/elonmusk/status/885916571549351936
https://x.com/elonmusk/status/885888274119540736
https://x.com/elonmusk/status/885884897381896192
https://x.com/elonmusk/status/885780183088680960
https://x.com/elonmusk/status/885635670315642880
https://x.com/elonmusk/status/884923882938933248
https://x.com/elonmusk/status/884653079936720896
https://x.com/elonmusk/status/883910005644251136
https://x.com/elonmusk/status/883900030163324928
https://x.com/elonmusk/status/883840893253451776
https://x.com/elonmusk/status/883632780264914944
https://x.com/elonmusk/status/882727063525797888
https://x.com/elonmusk/status/882117255407980544
https://x.com/elonmusk/status/881755501905588224
https://x.com/elonmusk/status/881573366565527552
https://x.com/elonmusk/status/880818231417511936
https://x.com/elonmusk/status/880679414274691072
https://x.com/elonmusk/status/880673804028194816
https://x.com/elonmusk/status/880665053162348544
https://x.com/elonmusk/status/880301259093270528
https://x.com/elonmusk/status/880255239881768960
https://x.com/elonmusk/status/880240745319325696
https://x.com/elonmusk/status/880240049677357056
https://x.com/elonmusk/status/879092174390001664
https://x.com/elonmusk/status/879085297526464512
https://x.com/elonmusk/status/878829325742518272
https://x.com/elonmusk/status/878824485280817152
https://x.com/elonmusk/status/878824283178287104
https://x.com/elonmusk/status/878822240699035648
https://x.com/elonmusk/status/878040258541043712
https://x.com/elonmusk/status/877928338358099968
https://x.com/elonmusk/status/877740365217882112
https://x.com/elonmusk/status/877469994593820672
https://x.com/elonmusk/status/876571952512507904
https://x.com/elonmusk/status/876564817179328512
https://x.com/elonmusk/status/876536951418925056
https://x.com/elonmusk/status/875913504451985408
https://x.com/elonmusk/status/875509067011153920
https://x.com/elonmusk/status/875070931537981440
https://x.com/elonmusk/status/874539511815954432
https://x.com/elonmusk/status/874506910120034304
https://x.com/elonmusk/status/874483570869272576
https://x.com/elonmusk/status/874029202768510976
https://x.com/elonmusk/status/873310575073255424
https://x.com/elonmusk/status/873210566826803200
https://x.com/elonmusk/status/873122114307371008
https://x.com/elonmusk/status/873121068172460032
https://x.com/elonmusk/status/873116351316938752
https://x.com/elonmusk/status/872935638944800768
https://x.com/elonmusk/status/872919207754711040
https://x.com/elonmusk/status/872906681851576320
https://x.com/elonmusk/status/872905016176025600
https://x.com/elonmusk/status/872893699511865344
https://x.com/elonmusk/status/872893125303222272
https://x.com/elonmusk/status/872869915337805824
https://x.com/elonmusk/status/872862122509647872
https://x.com/elonmusk/status/872322588919443456
https://x.com/elonmusk/status/871915360819204096
https://x.com/elonmusk/status/871805583761956864
https://x.com/elonmusk/status/871774429419667456
https://x.com/elonmusk/status/871603641970380800
https://x.com/elonmusk/status/871227498809368576
https://x.com/elonmusk/status/870411649622000000
https://x.com/elonmusk/status/870380036750168064
https://x.com/elonmusk/status/869781806467383296
https://x.com/elonmusk/status/867988709727129600
https://x.com/elonmusk/status/867667009839931392
https://x.com/elonmusk/status/867634302330093568
https://x.com/elonmusk/status/867239192774004736
https://x.com/elonmusk/status/866794741186183168
https://x.com/elonmusk/status/866794454731993088
https://x.com/elonmusk/status/866480356412727296
https://x.com/elonmusk/status/866472504541368320
https://x.com/elonmusk/status/866472074142822400
https://x.com/elonmusk/status/866171283167264768
https://x.com/elonmusk/status/865705983141494784
https://x.com/elonmusk/status/864722655651405824
https://x.com/elonmusk/status/863553417301512192
https://x.com/elonmusk/status/863550784012558336
https://x.com/elonmusk/status/863014220282998784
https://x.com/elonmusk/status/863014180835610624
https://x.com/elonmusk/status/863014096337162240
https://x.com/elonmusk/status/862571929345048576
https://x.com/elonmusk/status/862381399122128896
https://x.com/elonmusk/status/862221037835919360
https://x.com/elonmusk/status/862216356258758656
https://x.com/elonmusk/status/861271994288832512
https://x.com/elonmusk/status/860400588311244800
https://x.com/elonmusk/status/860378029515718656
https://x.com/elonmusk/status/860377370171121664
https://x.com/elonmusk/status/856354252209442816
https://x.com/elonmusk/status/856292321364631552
https://x.com/elonmusk/status/856196719746457600
https://x.com/elonmusk/status/848935705057280000
https://x.com/elonmusk/status/848415731502923776
https://x.com/elonmusk/status/848398971139629056
https://x.com/elonmusk/status/848036043240636416
https://x.com/elonmusk/status/847890916048338944
https://x.com/elonmusk/status/847883435100299264
https://x.com/elonmusk/status/847881536254955520
https://x.com/elonmusk/status/847594208219336704
https://x.com/elonmusk/status/847259545755820032
https://x.com/elonmusk/status/846772378067648512
https://x.com/elonmusk/status/846768171486855168
https://x.com/elonmusk/status/846668345998925824
https://x.com/elonmusk/status/845403535353143296
https://x.com/elonmusk/status/845294161125269504
https://x.com/elonmusk/status/845293825715154944
https://x.com/elonmusk/status/845293157977767936
https://x.com/elonmusk/status/845286206539685888
https://x.com/elonmusk/status/845283880080850944
https://x.com/elonmusk/status/845282733546921984
https://x.com/elonmusk/status/845282590030360576
https://x.com/elonmusk/status/845282298291339264
https://x.com/elonmusk/status/845281211626864640
https://x.com/elonmusk/status/845175921317335040
https://x.com/elonmusk/status/845175729885081600
https://x.com/elonmusk/status/841564430399807488
https://x.com/elonmusk/status/841563925707546624
https://x.com/elonmusk/status/841041891747545088
https://x.com/elonmusk/status/840774191049658368
https://x.com/elonmusk/status/840096176678420480
https://x.com/elonmusk/status/840032197637685248
https://x.com/elonmusk/status/838565081306677248
https://x.com/elonmusk/status/837113202030759936
https://x.com/elonmusk/status/835361919775100928
https://x.com/elonmusk/status/835351081945350144
https://x.com/elonmusk/status/835187859158020096
https://x.com/elonmusk/status/835178020604301312
https://x.com/elonmusk/status/834740218531962880
https://x.com/elonmusk/status/833329896168370176
https://x.com/elonmusk/status/832986598627106816
https://x.com/elonmusk/status/832868838479851520
https://x.com/elonmusk/status/832788691588296704
https://x.com/elonmusk/status/832647116816150528
https://x.com/elonmusk/status/832480331496185856
https://x.com/elonmusk/status/832085554619572224
https://x.com/elonmusk/status/832084918645596160
https://x.com/elonmusk/status/832084402473627648
https://x.com/elonmusk/status/831692803210096640
https://x.com/elonmusk/status/830148763578662912
https://x.com/elonmusk/status/829861775357071360
https://x.com/elonmusk/status/829447188325412864
https://x.com/elonmusk/status/829046669517860864
https://x.com/elonmusk/status/829027848434257920
https://x.com/elonmusk/status/828999653886550016
https://x.com/elonmusk/status/828998837578526720
https://x.com/elonmusk/status/828981873086865408
https://x.com/elonmusk/status/828320620463140864
https://x.com/elonmusk/status/828314321679704064
https://x.com/elonmusk/status/828309896122789888
https://x.com/elonmusk/status/828305244891336704
https://x.com/elonmusk/status/828304178644656128
https://x.com/elonmusk/status/828303494981550080
https://x.com/elonmusk/status/828297954314289152
https://x.com/elonmusk/status/828297251026001920
https://x.com/elonmusk/status/828292953798012928
https://x.com/elonmusk/status/828291645548408832
https://x.com/elonmusk/status/828291190965551104
https://x.com/elonmusk/status/828290224069419008
https://x.com/elonmusk/status/828287354741936128
https://x.com/elonmusk/status/828284048103579648
https://x.com/elonmusk/status/828282648711802880
https://x.com/elonmusk/status/828280866451374080
https://x.com/elonmusk/status/828004976228188160
https://x.com/elonmusk/status/828004231101706240
https://x.com/elonmusk/status/827999209085403136
https://x.com/elonmusk/status/827983309359763456
https://x.com/elonmusk/status/827954983710650368
https://x.com/elonmusk/status/827928366711967744
https://x.com/elonmusk/status/827926509197332480
https://x.com/elonmusk/status/825936326264360960
https://x.com/elonmusk/status/825502400454594560
https://x.com/elonmusk/status/825205236956483584
https://x.com/elonmusk/status/824300186834898944
https://x.com/elonmusk/status/824182450209386496
https://x.com/elonmusk/status/824182024479133696
https://x.com/elonmusk/status/824149662366126080
https://x.com/elonmusk/status/824147366844436480
https://x.com/elonmusk/status/824141566788898816
https://x.com/elonmusk/status/824056075217420288
https://x.com/elonmusk/status/824011724357373952
https://x.com/elonmusk/status/823632597284691968
https://x.com/elonmusk/status/823214178458476544
https://x.com/elonmusk/status/823213071309029376
https://x.com/elonmusk/status/822984601630953472
https://x.com/elonmusk/status/822930188040142848
https://x.com/elonmusk/status/822922507535560704
https://x.com/elonmusk/status/822130935588000000
https://x.com/elonmusk/status/822129390729326592
https://x.com/elonmusk/status/820935727651241984
https://x.com/elonmusk/status/820934434002063360
https://x.com/elonmusk/status/820932361915203584
https://x.com/elonmusk/status/820494936051097600
https://x.com/elonmusk/status/819660611357319168
https://x.com/elonmusk/status/818090148608868352
https://x.com/elonmusk/status/817123579343028224
https://x.com/elonmusk/status/812800512743514112
https://x.com/elonmusk/status/812703071427960832
https://x.com/elonmusk/status/812691977217024000
https://x.com/elonmusk/status/812106617072152576

In [14]:
for col in df.columns:
    missing_pct = df[col].isna().mean() * 100
    print(f"{col}: {missing_pct:.2f}% missing")

createdAt: 0.00% missing
url: 0.00% missing
fullText: 0.00% missing
Reposts: 0.14% missing
Comments: 1.46% missing
Likes: 0.14% missing

In [15]:
df_still_need_searching = df[
    (df['Likes'] == 0) &
    (df['Comments'] == 0) &
    (df['Reposts'] == 0)
]

In [16]:
df.size

323958

We moeten nog 366 tweets scrapen om de metadate hier van op te halen &rarr; het kan zijn dat deze gewoon al ge delete zijn

In [17]:
df_still_need_searching.size

366

We kunnen zien na deze check dat de url's zonder metadata tweets zijn NIET van elonmusk dus kunnen we ze gewoon verwijderen

In [18]:
for url in df_still_need_searching['url']:
    if "elonmusk" in str(url).lower():
        print(url)

In [19]:
df = df[df['url'].str.contains("elonmusk", case=False, na=False)]

In [20]:
df.size

323418

In [21]:
df['createdAt'] = pd.to_datetime(df['createdAt'])

df['DateKey'] = df['createdAt'].dt.strftime('%Y%m%d').astype(int)
df['TimeKey'] = df['createdAt'].dt.strftime('%H%M%S').astype(int)

In [22]:
df.drop(columns=['createdAt'],inplace=True)

In [23]:
df.head(2)

,url,fullText,Reposts,Comments,Likes,DateKey,TimeKey
1,https://x.com/elonmusk/status/1657261624867299339,https://t.co/Zjn6r15lrR,NaN,NaN,NaN,20230513,54856
3,https://x.com/elonmusk/status/1656900119202254854,Event Horizon Balance Beam,NaN,NaN,NaN,20230512,55226

In [24]:
for col in df.columns:
    missing_pct = df[col].isna().mean() * 100
    print(f"{col}: {missing_pct:.2f}% missing")

url: 0.00% missing
fullText: 0.00% missing
Reposts: 0.14% missing
Comments: 1.46% missing
Likes: 0.14% missing
DateKey: 0.00% missing
TimeKey: 0.00% missing

In [31]:
df = df[
    ~(
        (df['Likes'].isna()) &
        (df['Comments'].isna()) &
        (df['Reposts'].isna())
    )
]

In [35]:
df.shape

(53827, 7)

In [38]:
df.rename(columns={
    'fullText' : 'Text'
},inplace=True)

In [36]:
df.head()

,url,fullText,Reposts,Comments,Likes,DateKey,TimeKey
90,https://x.com/elonmusk/status/928675794372608000,"""If one day, my words are against science, cho...",49919.0,NaN,104722.0,20171109,172857
91,https://x.com/elonmusk/status/928335114353831936,Atatürk Anıtkabir https://t.co/al3wt0njr6,34752.0,NaN,104823.0,20171108,185513
92,https://x.com/elonmusk/status/924389383792312448,@uncover007 500 ft so far. Should be 2 miles l...,207.0,NaN,2128.0,20171028,213618
93,https://x.com/elonmusk/status/924387972161552512,Picture of The Boring Company LA tunnel taken ...,8834.0,NaN,58882.0,20171028,213041
94,https://x.com/elonmusk/status/923576364652953600,"Whiskey, fire, s’mores and JC\r\n\r\nAlso, hot...",1193.0,NaN,11563.0,20171026,154539

In [41]:
df.to_csv(ROOT / "data" / "processed" / "elonmusk.csv", index=False)