In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("../../../raw/tweets/WhiteHouse/WhiteHouse_tweets.csv")
df.head(10)

,date,username,text,replies,reposts,likes,bookmarks,views
0,2026-03-21 18:57:57,WhiteHouse,NaN,156,255,907,31,154980
1,2026-03-21 18:57:41,WhiteHouse,The United States and Japan continued to stren...,1129,2992,13264,375,271102
2,2026-03-21 17:52:23,WhiteHouse,"NO MORE WAITING, NO MORE GAMES!",11063,11699,52704,1836,6345973
3,2026-03-21 17:51:59,WhiteHouse,"NO MORE WAITING, NO MORE GAMES!",3441,8889,40067,813,2966036
4,2026-03-21 17:17:42,WhiteHouse,"Air superiority: achieved.\n8,000+ targets: el...",4399,3793,16922,418,648078
5,2026-03-21 15:48:42,WhiteHouse,"""If the Radical Left Democrats don’t immediate...",5421,10961,35063,741,820185
6,2026-03-20 22:39:45,WhiteHouse,WHEELS UP. FLAGS HIGH.,904,1712,13796,195,215588
7,2026-03-20 21:23:55,WhiteHouse,"""We are getting very close to meeting our obje...",5471,5673,19471,755,1212773
8,2026-03-20 21:14:32,WhiteHouse,MORE,69,153,553,32,69359
9,2026-03-20 21:14:32,WhiteHouse,The Trump administration is committed to WINNI...,637,1108,4014,259,288759

In [23]:
df['date'] = pd.to_datetime(df['date'], errors="coerce")

In [24]:
df['time'] = df['date'].dt.time
df['date'] = df['date'].dt.date

In [25]:
df.head()

,date,username,text,replies,reposts,likes,bookmarks,views,time
0,2026-03-21,WhiteHouse,NaN,156,255,907,31,154980,18:57:57
1,2026-03-21,WhiteHouse,The United States and Japan continued to stren...,1129,2992,13264,375,271102,18:57:41
2,2026-03-21,WhiteHouse,"NO MORE WAITING, NO MORE GAMES!",11063,11699,52704,1836,6345973,17:52:23
3,2026-03-21,WhiteHouse,"NO MORE WAITING, NO MORE GAMES!",3441,8889,40067,813,2966036,17:51:59
4,2026-03-21,WhiteHouse,"Air superiority: achieved.\n8,000+ targets: el...",4399,3793,16922,418,648078,17:17:42