In [56]:
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import re
import time
import pandas as pd
from datetime import datetime
import os
from dotenv import load_dotenv

In [57]:
load_dotenv()
end_date = datetime.today().strftime("%Y-%m-%d")
scroll_pause = 2  # seconden tussen scrolls

In [58]:
my_twitter_email = os.getenv("my_twitter_email")
my_twitter_username = os.getenv("my_twitter_username")
my_twitter_password = os.getenv("my_twitter_password")

In [59]:
options = uc.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument("--disable-notifications")

In [60]:
driver = uc.Chrome(version_main=143, options=options)
time.sleep(5)

In [61]:
# Ga naar loginpagina
driver.get("https://twitter.com/login")
time.sleep(5)  # wacht tot de pagina volledig geladen is

In [62]:
username_input = driver.find_element(By.NAME, "text")
username_input.send_keys(my_twitter_username)
time.sleep(1)
username_input.send_keys(Keys.ENTER)
time.sleep(3)

In [63]:
try:
    password_input = driver.find_element(By.NAME, "password")
    password_input.send_keys(my_twitter_password)
    time.sleep(5)
    password_input.send_keys(Keys.ENTER)
    time.sleep(5)
except:
    print("Geen wachtwoord invoer vereist of al ingelogd.")

In [64]:
usernames_we_wanna_scrape = ["elonmusk", "realDonaldTrump"]

In [65]:
def twitter_handle(username : str):
    driver.get(f"https://twitter.com/{username}")
    time.sleep(7)  # wachten tot pagina laadt
    # zorg dat cookies worden ge accepteert indien nodig:
    try:
        cookie_button = driver.find_element(By.XPATH, '//button[contains(., "Accept all cookies")]')
        cookie_button.click()
        print("Cookies geaccepteerd.")
        time.sleep(2)
    except:
        print("Geen cookie-wall gevonden of al geaccepteerd.")

In [66]:
tweets_data = []

In [67]:
def human_scroll(driver, total_scroll=3000, step=300, pause=0.3):
    scrolled = 0
    while scrolled < total_scroll:
        driver.execute_script(f"window.scrollBy(0, {step});")
        scrolled += step
        time.sleep(pause)

In [68]:
def save_to_csv():
    df = pd.DataFrame(tweets_data, columns=["Date", "Username", "Content", "Replies", "Reposts", "Likes", "Bookmarks", "Views"])
    df['Date'] = df['Date'].dt.strftime('%Y-%m-%d %H:%M')
    df['Time'] = pd.to_datetime(df['Date']).dt.time
    df['Date'] = pd.to_datetime(df['Date']).dt.date
    print(f"{len(df)} tweets opgeslagen!")
    return df

In [ ]:
# Instellingen
target_date = end_date  # Stop met scrapen bij tweets ouder dan 1 jan 2026
tweets_ids = set() 

for user in usernames_we_wanna_scrape:
    twitter_handle(username=user)
    stop_scraping = False
    print(f"Start met scrapen tot aan {target_date} van {user}...")
    while stop_scraping == False:
        if stop_scraping:
            break
            
        # Zoek alle zichtbare tweets
        articles = driver.find_elements(By.XPATH, '//article[@role="article" and @data-testid="tweet"]')
        
        for article in articles:
            try:
                # 1. Datum ophalen
                time_elem = article.find_element(By.XPATH, './/time')
                date_str = time_elem.get_attribute("datetime")
                tweet_date = datetime.fromisoformat(date_str.replace("Z", "+00:00")).replace(tzinfo=None)

                # 2. Unieke ID check
                tweet_id = article.find_element(By.XPATH, './/time/..').get_attribute('href')
                tweet_username = tweet_id.split("/")[3]
                
                print(f"date: {tweet_date}\ntweet_usernam: {tweet_username}")
                
                if tweet_id in tweets_ids:
                    continue

                if tweet_username != user:
                    print(f"username: {tweet_username} is not {user}")
                    continue

                # 3. Check pinned
                try:
                    social_context = article.find_element(By.CSS_SELECTOR, "div[data-testid='socialContext']")
                    is_pinned = "Pinned" in social_context.text
                except:
                    is_pinned = False
                    
                print(f"pinned: {is_pinned}")
                    

                # 4. Beslissing opslaan
                # Opslaan alleen als pinned of tweet van vandaag
                if is_pinned and tweet_date.strftime("%Y-%m-%d") < target_date:
                    print(f"tweet: {tweet_date} is pinned and has older date")
                    continue
                elif tweet_date.strftime("%Y-%m-%d") < target_date:
                    stop_scraping = True
                    break
                
                
                

                # 5. Tekst en statistieken ophalen
                text = article.find_element(By.XPATH, './/div[@data-testid="tweetText"]').text
                stats_group = article.find_element(By.XPATH, './/div[@role="group"]')
                label = stats_group.get_attribute("aria-label")

                def parse_stat(pattern, text):
                    match = re.search(pattern, text.lower())
                    if match:
                        return int(re.sub(r'[^\d]', '', match.group(1)))
                    return 0

                replies = parse_stat(r'(\d[\d\.,]*)\s+replies', label)
                reposts = parse_stat(r'(\d[\d\.,]*)\s+reposts', label)
                likes = parse_stat(r'(\d[\d\.,]*)\s+likes', label)
                bookmarks = parse_stat(r'(\d[\d\.,]*)\s+bookmarks', label)
                views = parse_stat(r'(\d[\d\.,]*)\s+views', label)

                # Opslaan
                tweets_data.append([tweet_date, tweet_username, text, replies, reposts, likes, bookmarks, views])
                tweets_ids.add(tweet_id)
                print(f"Opgeslagen: {tweet_date.strftime('%Y-%m-%d %H:%M')} | @{tweet_username} | Likes: {likes}")

            except Exception as e:
                # Optioneel: print(e) voor debug
                continue

        
        # Scroll naar beneden om nieuwe tweets te laden
        human_scroll(driver, total_scroll=2500, step=250, pause=0.4)
        time.sleep(scroll_pause)

print(f"Klaar! {len(tweets_data)} tweets verzameld.")

Cookies geaccepteerd.
Start met scrapen tot aan 2026-01-31 van elonmusk...
date: 2026-01-31 21:10:13
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 21:10 | @elonmusk | Likes: 2121
date: 2026-01-31 20:44:04
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 20:44 | @elonmusk | Likes: 3933
date: 2026-01-31 19:43:07
tweet_usernam: Starlink
username: Starlink is not elonmusk
date: 2026-01-31 18:16:17
tweet_usernam: AdamLowisz
username: AdamLowisz is not elonmusk
date: 2026-01-31 18:29:40
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 18:29 | @elonmusk | Likes: 18178
date: 2026-01-31 21:10:13
tweet_usernam: elonmusk
date: 2026-01-31 20:44:04
tweet_usernam: elonmusk
date: 2026-01-31 19:43:07
tweet_usernam: Starlink
username: Starlink is not elonmusk
date: 2026-01-31 18:16:17
tweet_usernam: AdamLowisz
username: AdamLowisz is not elonmusk
date: 2026-01-31 18:29:40
tweet_usernam: elonmusk
date: 2026-01-31 18:06:11
tweet_usernam: AdamLowisz
username: AdamLowisz is not elonmusk
date: 2026-01-31 18:14:45
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 18:14 | @elonmusk | Likes: 26853
date: 2026-01-31 18:08:33
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 18:08 | @elonmusk | Likes: 13985
date: 2026-01-31 18:06:11
tweet_usernam: AdamLowisz
username: AdamLowisz is not elonmusk
date: 2026-01-31 18:14:45
tweet_usernam: elonmusk
date: 2026-01-31 18:08:33
tweet_usernam: elonmusk
date: 2026-01-31 18:06:10
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 18:06 | @elonmusk | Likes: 18301
date: 2026-01-31 18:03:42
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 18:03 | @elonmusk | Likes: 23186
date: 2026-01-31 14:48:44
tweet_usernam: grok
username: grok is not elonmusk
date: 2026-01-31 17:57:47
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 17:57 | @elonmusk | Likes: 8031
date: 2026-01-31 17:56:33
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 17:56 | @elonmusk | Likes: 51208
date: 2026-01-31 18:06:10
tweet_usernam: elonmusk
date: 2026-01-31 18:03:42
tweet_usernam: elonmusk
date: 2026-01-31 14:48:44
tweet_usernam: grok
username: grok is not elonmusk
date: 2026-01-31 17:57:47
tweet_usernam: elonmusk
date: 2026-01-31 17:56:33
tweet_usernam: elonmusk
date: 2026-01-31 17:54:08
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 17:54 | @elonmusk | Likes: 21462
date: 2026-01-31 14:54:46
tweet_usernam: teslaownersSV
username: teslaownersSV is not elonmusk
date: 2026-01-31 08:29:33
tweet_usernam: _SFTahoe
username: _SFTahoe is not elonmusk
date: 2026-01-31 15:05:40
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 17:54:08
tweet_usernam: elonmusk
date: 2026-01-31 14:54:46
tweet_usernam: teslaownersSV
username: teslaownersSV is not elonmusk
date: 2026-01-31 08:29:33
tweet_usernam: _SFTahoe
username: _SFTahoe is not elonmusk
date: 2026-01-31 15:05:40
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 15:07:45
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 15:07 | @elonmusk | Likes: 7691
date: 2026-01-31 15:07:29
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 15:07 | @elonmusk | Likes: 64513
date: 2026-01-31 01:29:30
tweet_usernam: Petermarocco
username: Petermarocco is not elonmusk
date: 2026-01-31 15:07:45
tweet_usernam: elonmusk
date: 2026-01-31 15:07:29
tweet_usernam: elonmusk
date: 2026-01-31 01:29:30
tweet_usernam: Petermarocco
username: Petermarocco is not elonmusk
date: 2026-01-31 15:04:12
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 15:04 | @elonmusk | Likes: 95336
date: 2026-01-31 14:27:31
tweet_usernam: MELANIATRUMP
username: MELANIATRUMP is not elonmusk
date: 2026-01-31 08:12:48
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 14:54:19
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:54 | @elonmusk | Likes: 85290
date: 2026-01-31 14:51:02
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:51 | @elonmusk | Likes: 17196
date: 2026-01-31 14:50:47
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:50 | @elonmusk | Likes: 87711
date: 2026-01-31 14:27:31
tweet_usernam: MELANIATRUMP
username: MELANIATRUMP is not elonmusk
date: 2026-01-31 08:12:48
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 14:54:19
tweet_usernam: elonmusk
date: 2026-01-31 14:51:02
tweet_usernam: elonmusk
date: 2026-01-31 14:50:47
tweet_usernam: elonmusk
date: 2026-01-31 14:48:38
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:48 | @elonmusk | Likes: 34926
date: 2026-01-31 14:47:51
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:47 | @elonmusk | Likes: 16863
date: 2026-01-31 14:38:37
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 14:38 | @elonmusk | Likes: 125766
date: 2026-01-31 14:50:47
tweet_usernam: elonmusk
date: 2026-01-31 14:48:38
tweet_usernam: elonmusk
date: 2026-01-31 14:47:51
tweet_usernam: elonmusk
date: 2026-01-31 14:38:37
tweet_usernam: elonmusk
date: 2026-01-31 14:03:54
tweet_usernam: jgebbia
username: jgebbia is not elonmusk
date: 2026-01-31 07:42:04
tweet_usernam: ezrafeilden
username: ezrafeilden is not elonmusk
date: 2026-01-31 06:59:57
tweet_usernam: niccruzpatane
username: niccruzpatane is not elonmusk
date: 2026-01-31 05:35:44
tweet_usernam: niccruzpatane
username: niccruzpatane is not elonmusk
date: 2026-01-31 06:46:39
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 14:03:54
tweet_usernam: jgebbia
username: jgebbia is not elonmusk
date: 2026-01-31 07:42:04
tweet_usernam: ezrafeilden
username: ezrafeilden is not elonmusk
date: 2026-01-31 06:59:57
tweet_usernam: niccruzpatane
username: niccruzpatane is not elonmusk
date: 2026-01-31 05:35:44
tweet_usernam: niccruzpatane
username: niccruzpatane is not elonmusk
date: 2026-01-31 06:46:39
tweet_usernam: cb_doge
username: cb_doge is not elonmusk
date: 2026-01-31 06:36:01
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 06:36 | @elonmusk | Likes: 35883
date: 2026-01-31 06:29:32
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 06:29 | @elonmusk | Likes: 85798
date: 2026-01-31 05:49:13
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 05:49 | @elonmusk | Likes: 65683
date: 2026-01-31 05:29:05
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 05:29 | @elonmusk | Likes: 21737
date: 2026-01-31 04:26:13
tweet_usernam: billmaher
username: billmaher is not elonmusk
date: 2026-01-31 06:36:01
tweet_usernam: elonmusk
date: 2026-01-31 06:29:32
tweet_usernam: elonmusk
date: 2026-01-31 05:49:13
tweet_usernam: elonmusk
date: 2026-01-31 05:29:05
tweet_usernam: elonmusk
date: 2026-01-31 04:26:13
tweet_usernam: billmaher
username: billmaher is not elonmusk
date: 2026-01-31 05:16:35
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 05:16 | @elonmusk | Likes: 24854
date: 2026-01-31 02:01:43
tweet_usernam: realDonaldTrump
username: realDonaldTrump is not elonmusk
date: 2026-01-30 19:00:22
tweet_usernam: BiblicalBeauty
username: BiblicalBeauty is not elonmusk
date: 2026-01-31 01:11:41
tweet_usernam: Eric_Schmitt
username: Eric_Schmitt is not elonmusk
date: 2026-01-31 02:10:34
tweet_usernam: elonmusk
pinned: False
Opgeslagen: 2026-01-31 02:10 | @elonmusk | Likes: 25345
date: 2026-01-30 23:03:36
tweet_usernam: elonmusk
pinned: False
Geen cookie-wall gevonden of al geaccepteerd.
Start met scrapen tot aan 2026-01-31 van realDonaldTrump...
date: 2026-01-31 18:16:33
tweet_usernam: MELANIATRUMP
username: MELANIATRUMP is not realDonaldTrump
date: 2026-01-31 02:01:43
tweet_usernam: realDonaldTrump
pinned: False
Opgeslagen: 2026-01-31 02:01 | @realDonaldTrump | Likes: 243890
date: 2026-01-26 17:05:08
tweet_usernam: realDonaldTrump
pinned: False
Klaar! 26 tweets verzameld.
26 tweets opgeslagen!

,Date,Username,Content,Replies,Reposts,Likes,Bookmarks,Views,Time
0,2026-01-31,elonmusk,Just the very early stages of the singularity....,679,271,2121,120,343425,21:10:00
1,2026-01-31,elonmusk,Definitely,932,569,3933,183,911588,20:44:00
2,2026-01-31,elonmusk,This is why,1855,4789,18178,814,1806902,18:29:00
3,2026-01-31,elonmusk,It has indeed somehow become even worse,1841,4155,26853,1234,3071813,18:14:00
4,2026-01-31,elonmusk,Delaware Supreme is saving the state,989,1916,13985,255,2059963,18:08:00
5,2026-01-31,elonmusk,,1663,1916,18301,464,2845506,18:06:00
6,2026-01-31,elonmusk,China electricity generation is still growing ...,3225,3866,23186,1776,5389597,18:03:00
7,2026-01-31,elonmusk,Space is huge,1908,908,8031,235,6655448,17:57:00
8,2026-01-31,elonmusk,Still remains true,2642,7091,51208,996,3984037,17:56:00
9,2026-01-31,elonmusk,Yes,2303,3749,21462,391,2877435,17:54:00
10,2026-01-31,elonmusk,Yes,1488,1350,7691,286,2963969,15:07:00
11,2026-01-31,elonmusk,Congratulations to the \n@FLOTUS\n!,2913,7277,64513,887,25556632,15:07:00
12,2026-01-31,elonmusk,There will be thousands of court cases of chil...,5501,20635,95336,2633,3791305,15:04:00
13,2026-01-31,elonmusk,"Oops, did I say 1 million? \n\nI meant to say ...",5154,4993,85290,1526,10039920,14:54:00
14,2026-01-31,elonmusk,Absolutely,2086,3117,17196,399,1761455,14:51:00
15,2026-01-31,elonmusk,That is the key question. Epstein and Maxwell ...,6366,16675,87711,2738,8827370,14:50:00
16,2026-01-31,elonmusk,"Solar is not A source of energy, it is THE sou...",4653,4357,34926,1771,5108461,14:48:00
17,2026-01-31,elonmusk,Grokipedia is the future,2138,2983,16863,551,1521479,14:47:00
18,2026-01-31,elonmusk,What matters is not release of some subset of ...,13288,21580,125766,5389,17673033,14:38:00
19,2026-01-31,elonmusk,100GW/year of solar-powered AI satellites requ...,3716,5774,35883,1907,6902882,06:36:00
20,2026-01-31,elonmusk,The balance of power is changing,5267,10644,85798,6333,37846429,06:29:00
21,2026-01-31,elonmusk,The satellites will actually be so far apart t...,7149,9116,65683,3997,14431219,05:49:00
22,2026-01-31,elonmusk,That’s my favorite part,2056,2762,21737,1367,10011894,05:29:00
23,2026-01-31,elonmusk,It really is that good,2248,3096,24854,733,5768453,05:16:00
24,2026-01-31,elonmusk,Exactly,3537,3376,25345,1670,15396855,02:10:00
25,2026-01-31,realDonaldTrump,"Last night I saw, “MELANIA,” for the second ti...",29998,31049,243890,5450,24349857,02:01:00

In [74]:
big_file = pd.concat([save_to_csv(), pd.read_csv("../../raw/elonmusk_tweets.csv")],ignore_index=True)

26 tweets opgeslagen!

In [75]:
big_file.set_index('Date', inplace=True)

In [76]:
big_file.head()

,Username,Content,Replies,Reposts,Likes,Bookmarks,Views,Time
Date,,,,,,,,
2026-01-31,elonmusk,Just the very early stages of the singularity....,679,271,2121,120,343425,21:10:00
2026-01-31,elonmusk,Definitely,932,569,3933,183,911588,20:44:00
2026-01-31,elonmusk,This is why,1855,4789,18178,814,1806902,18:29:00
2026-01-31,elonmusk,It has indeed somehow become even worse,1841,4155,26853,1234,3071813,18:14:00
2026-01-31,elonmusk,Delaware Supreme is saving the state,989,1916,13985,255,2059963,18:08:00

In [77]:
big_file.to_csv("../../raw/elonmusk_tweets.csv", index=True)